R4DS Study Group - Week 31
================
Pierrette Lo
11/6/2020

  - [This week’s assignment](#this-weeks-assignment)
  - [Ch 13:1 Introduction](#ch-131-introduction)
  - [Ch 13:2 nycflights13](#ch-132-nycflights13)
  - [Ch 13:3 Keys](#ch-133-keys)

## This week’s assignment

  - Chapter 13, sections 1-3

<!-- end list -->

``` r
library(tidyverse)
library(nycflights13)
```

## Ch 13:1 Introduction

### Notes

  - Our Beat AML database is a relational database
  - Most people access it using the web interface, but that gets clunky
    for more complex queries
  - If you know SQL, you can request back-end access to the database so
    you can perform more complex queries. You can also write SQL queries
    in RStudio, so you can pull data from the database directly into R\!
  - That is definitely beyond the scope of this R4DS chapter, but if you
    understand the concepts in this chapter, you’ll be in a good
    position to learn SQL.

Some links to SQL learning resources (I haven’t used most of these
myself, but have seen them recommended by others):

  - good resource for looking up terms:
    <https://www.w3schools.com/sql/default.asp>
  - interactive tutorial: <https://selectstarsql.com/>
  - interactive tutorial: <https://sqlbolt.com/>
  - blog post about using SQL in RStudio:
    <https://irene.rbind.io/post/using-sql-in-rstudio/>
  - cartoon explaining how SQL queries work:
    <https://mobile.twitter.com/b0rk/status/1184571894722449409/photo/1>

## Ch 13:2 nycflights13

### Exercises

> 1.  Imagine you wanted to draw (approximately) the route each plane
>     flies from its origin to its destination. What variables would you
>     need? What tables would you need to combine?

``` r
glimpse(flights)
```

    ## Rows: 336,776
    ## Columns: 19
    ## $ year           <int> 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013...
    ## $ month          <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ day            <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ dep_time       <int> 517, 533, 542, 544, 554, 554, 555, 557, 557, 558, 55...
    ## $ sched_dep_time <int> 515, 529, 540, 545, 600, 558, 600, 600, 600, 600, 60...
    ## $ dep_delay      <dbl> 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2, -2,...
    ## $ arr_time       <int> 830, 850, 923, 1004, 812, 740, 913, 709, 838, 753, 8...
    ## $ sched_arr_time <int> 819, 830, 850, 1022, 837, 728, 854, 723, 846, 745, 8...
    ## $ arr_delay      <dbl> 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -3, 7,...
    ## $ carrier        <chr> "UA", "UA", "AA", "B6", "DL", "UA", "B6", "EV", "B6"...
    ## $ flight         <int> 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79, 301...
    ## $ tailnum        <chr> "N14228", "N24211", "N619AA", "N804JB", "N668DN", "N...
    ## $ origin         <chr> "EWR", "LGA", "JFK", "JFK", "LGA", "EWR", "EWR", "LG...
    ## $ dest           <chr> "IAH", "IAH", "MIA", "BQN", "ATL", "ORD", "FLL", "IA...
    ## $ air_time       <dbl> 227, 227, 160, 183, 116, 150, 158, 53, 140, 138, 149...
    ## $ distance       <dbl> 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 944, 73...
    ## $ hour           <dbl> 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6...
    ## $ minute         <dbl> 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59...
    ## $ time_hour      <dttm> 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013-01-0...

`flights` - `flight`, `origin`, `dest`

`airports` - `lat`, `lon`

These tables are linked by `airports$faa` = `flights$origin` or
`flights$dest`

The [solutions
manual](https://jrnold.github.io/r4ds-exercise-solutions/relational-data.html#exercise-13.2.1)
works through the steps to actually make this plot. We can go back and
look at this once we’ve learned more about joins.

> 2.  I forgot to draw the relationship between `weather` and
>     `airports.` What is the relationship and how should it appear in
>     the diagram?

These tables are linked by `airports$faa` = `weather$origin`

> 3.  `weather` only contains information for the origin (NYC) airports.
>     If it contained weather records for all airports in the USA, what
>     additional relation would it define with `flights`?

`weather$faa` would be linked to `flights$dest`

> 4.  We know that some days of the year are “special”, and fewer people
>     than usual fly on them. How might you represent that data as a
>     data frame? What would be the primary keys of that table? How
>     would it connect to the existing tables?

`special_days` table, with columns:

  - year
  - month
  - day
  - description (e.g. “Christmas Day”)

The primary keys – ie. unique identifier for each special day – would be
the combination of `year`, `month`, and `day`. (You need `year` for the
holidays that don’t occur on the same date each year, e.g. Thanksgiving
Day.)

## Ch 13:3 Keys

> 1.  Add a surrogate key to `flights`.

``` r
flights %>% 
  mutate(surrogate_key = row_number(), 
         .before = 1)
```

    ## # A tibble: 336,776 x 20
    ##    surrogate_key  year month   day dep_time sched_dep_time dep_delay arr_time
    ##            <int> <int> <int> <int>    <int>          <int>     <dbl>    <int>
    ##  1             1  2013     1     1      517            515         2      830
    ##  2             2  2013     1     1      533            529         4      850
    ##  3             3  2013     1     1      542            540         2      923
    ##  4             4  2013     1     1      544            545        -1     1004
    ##  5             5  2013     1     1      554            600        -6      812
    ##  6             6  2013     1     1      554            558        -4      740
    ##  7             7  2013     1     1      555            600        -5      913
    ##  8             8  2013     1     1      557            600        -3      709
    ##  9             9  2013     1     1      557            600        -3      838
    ## 10            10  2013     1     1      558            600        -2      753
    ## # ... with 336,766 more rows, and 12 more variables: sched_arr_time <int>,
    ## #   arr_delay <dbl>, carrier <chr>, flight <int>, tailnum <chr>, origin <chr>,
    ## #   dest <chr>, air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>,
    ## #   time_hour <dttm>

> 2.  Identify the keys in the following datasets. (You might need to
>     install some packages and read some documentation.)

> 2.1 `Lahman::Batting`

First install the `Lahman` package, then check out the help (`?Batting`)
and preview the `Batting` table.

``` r
# install.packages("Lahman")

glimpse(Lahman::Batting)
```

    ## Rows: 107,429
    ## Columns: 22
    ## $ playerID <chr> "abercda01", "addybo01", "allisar01", "allisdo01", "ansonc...
    ## $ yearID   <int> 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871...
    ## $ stint    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ teamID   <fct> TRO, RC1, CL1, WS3, RC1, FW1, RC1, BS1, FW1, BS1, CL1, CL1...
    ## $ lgID     <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ G        <int> 1, 25, 29, 27, 25, 12, 1, 31, 1, 18, 22, 1, 10, 3, 20, 29,...
    ## $ AB       <int> 4, 118, 137, 133, 120, 49, 4, 157, 5, 86, 89, 3, 36, 15, 9...
    ## $ R        <int> 0, 30, 28, 28, 29, 9, 0, 66, 1, 13, 18, 0, 6, 7, 24, 26, 0...
    ## $ H        <int> 0, 32, 40, 44, 39, 11, 1, 63, 1, 13, 27, 0, 7, 6, 33, 32, ...
    ## $ X2B      <int> 0, 6, 4, 10, 11, 2, 0, 10, 1, 2, 1, 0, 0, 0, 9, 3, 0, 0, 1...
    ## $ X3B      <int> 0, 0, 5, 2, 3, 1, 0, 9, 0, 1, 10, 0, 0, 0, 1, 3, 0, 0, 1, ...
    ## $ HR       <int> 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0...
    ## $ RBI      <int> 0, 13, 19, 27, 16, 5, 2, 34, 1, 11, 18, 0, 1, 5, 21, 23, 0...
    ## $ SB       <int> 0, 8, 3, 1, 6, 0, 0, 11, 0, 1, 0, 0, 2, 2, 4, 4, 0, 0, 3, ...
    ## $ CS       <int> 0, 1, 1, 1, 2, 1, 0, 6, 0, 0, 1, 0, 0, 0, 0, 4, 0, 0, 1, 0...
    ## $ BB       <int> 0, 4, 2, 0, 2, 0, 1, 13, 0, 0, 3, 1, 2, 0, 2, 9, 0, 0, 4, ...
    ## $ SO       <int> 0, 0, 5, 2, 1, 1, 0, 1, 0, 0, 4, 0, 0, 0, 2, 2, 3, 0, 2, 0...
    ## $ IBB      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ HBP      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ SH       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ SF       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ GIDP     <int> 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0...

I think the primary keys – i.e. minimum unique identifier for each
observation – are `playerID`, `yearID`, and `stint`. Check that each
combination of player/year/stint only occurs once:

``` r
Lahman::Batting %>% 
  count(playerID, yearID, stint) %>% 
  filter(n > 1)
```

    ## [1] playerID yearID   stint    n       
    ## <0 rows> (or 0-length row.names)

Note that if you remove `stint` from the above code, you get many rows
where `n` = 2, indicating that many players played 2 stints per year.

``` r
Lahman::Batting %>% 
  count(playerID, yearID) %>% 
  filter(n > 1) %>% 
  nrow()
```

    ## [1] 7578

> 2.2 babynames::babynames

``` r
# install.packages("babynames")

glimpse(babynames::babynames)
```

    ## Rows: 1,924,665
    ## Columns: 5
    ## $ year <dbl> 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 18...
    ## $ sex  <chr> "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F...
    ## $ name <chr> "Mary", "Anna", "Emma", "Elizabeth", "Minnie", "Margaret", "Id...
    ## $ n    <int> 7065, 2604, 2003, 1939, 1746, 1578, 1472, 1414, 1320, 1288, 12...
    ## $ prop <dbl> 0.07238359, 0.02667896, 0.02052149, 0.01986579, 0.01788843, 0....

Primary keys: year, sex, and name (some names are used by each sex)

``` r
babynames::babynames %>% 
  count(year, sex, name) %>% 
  filter(n > 1)
```

    ## # A tibble: 0 x 4
    ## # ... with 4 variables: year <dbl>, sex <chr>, name <chr>, n <int>

> 2.3 nasaweather::atmos

``` r
# install.packages("nasaweather")

glimpse(nasaweather::atmos)
```

    ## Rows: 41,472
    ## Columns: 11
    ## $ lat       <dbl> 36.200000, 33.704348, 31.208696, 28.713043, 26.217391, 23...
    ## $ long      <dbl> -113.8000, -113.8000, -113.8000, -113.8000, -113.8000, -1...
    ## $ year      <int> 1995, 1995, 1995, 1995, 1995, 1995, 1995, 1995, 1995, 199...
    ## $ month     <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
    ## $ surftemp  <dbl> 272.7, 279.5, 284.7, 289.3, 292.2, 294.1, 295.0, 298.3, 3...
    ## $ temp      <dbl> 272.1, 282.2, 285.2, 290.7, 292.7, 293.6, 294.6, 296.9, 2...
    ## $ pressure  <dbl> 835, 940, 960, 990, 1000, 1000, 1000, 1000, 1000, 1000, 1...
    ## $ ozone     <dbl> 304, 304, 298, 276, 274, 264, 258, 252, 250, 250, 248, 24...
    ## $ cloudlow  <dbl> 7.5, 11.5, 16.5, 20.5, 26.0, 30.0, 29.5, 26.5, 27.5, 26.0...
    ## $ cloudmid  <dbl> 34.5, 32.5, 26.0, 14.5, 10.5, 9.5, 11.0, 17.5, 18.5, 16.5...
    ## $ cloudhigh <dbl> 26.0, 20.0, 16.0, 13.0, 7.5, 8.0, 14.5, 19.5, 22.5, 21.0,...

Primary keys: lat, long, year, month

``` r
nasaweather::atmos %>% 
  count(lat, long, year, month) %>% 
  filter(n > 1)
```

    ## # A tibble: 0 x 5
    ## # ... with 5 variables: lat <dbl>, long <dbl>, year <int>, month <int>, n <int>

> 2.4 fueleconomy::vehicles

``` r
# install.packages("fueleconomy")

glimpse(fueleconomy::vehicles)
```

    ## Rows: 33,442
    ## Columns: 12
    ## $ id    <dbl> 13309, 13310, 13311, 14038, 14039, 14040, 14834, 14835, 14836...
    ## $ make  <chr> "Acura", "Acura", "Acura", "Acura", "Acura", "Acura", "Acura"...
    ## $ model <chr> "2.2CL/3.0CL", "2.2CL/3.0CL", "2.2CL/3.0CL", "2.3CL/3.0CL", "...
    ## $ year  <dbl> 1997, 1997, 1997, 1998, 1998, 1998, 1999, 1999, 1999, 1995, 1...
    ## $ class <chr> "Subcompact Cars", "Subcompact Cars", "Subcompact Cars", "Sub...
    ## $ trans <chr> "Automatic 4-spd", "Manual 5-spd", "Automatic 4-spd", "Automa...
    ## $ drive <chr> "Front-Wheel Drive", "Front-Wheel Drive", "Front-Wheel Drive"...
    ## $ cyl   <dbl> 4, 4, 6, 4, 4, 6, 4, 4, 6, 5, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6...
    ## $ displ <dbl> 2.2, 2.2, 3.0, 2.3, 2.3, 3.0, 2.3, 2.3, 3.0, 2.5, 2.5, 3.2, 2...
    ## $ fuel  <chr> "Regular", "Regular", "Regular", "Regular", "Regular", "Regul...
    ## $ hwy   <dbl> 26, 28, 26, 27, 29, 26, 27, 29, 26, 23, 23, 22, 23, 22, 23, 2...
    ## $ cty   <dbl> 20, 22, 18, 19, 21, 17, 20, 21, 17, 18, 18, 17, 18, 17, 17, 1...

Primary key: id

``` r
n_distinct(fueleconomy::vehicles$id) == nrow(fueleconomy::vehicles)
```

    ## [1] TRUE

> 2.5 ggplot2::diamonds

``` r
glimpse(diamonds)
```

    ## Rows: 53,940
    ## Columns: 10
    ## $ carat   <dbl> 0.23, 0.21, 0.23, 0.29, 0.31, 0.24, 0.24, 0.26, 0.22, 0.23,...
    ## $ cut     <ord> Ideal, Premium, Good, Premium, Good, Very Good, Very Good, ...
    ## $ color   <ord> E, E, E, I, J, J, I, H, E, H, J, J, F, J, E, E, I, J, J, J,...
    ## $ clarity <ord> SI2, SI1, VS1, VS2, SI2, VVS2, VVS1, SI1, VS2, VS1, SI1, VS...
    ## $ depth   <dbl> 61.5, 59.8, 56.9, 62.4, 63.3, 62.8, 62.3, 61.9, 65.1, 59.4,...
    ## $ table   <dbl> 55, 61, 65, 58, 58, 57, 57, 55, 61, 61, 55, 56, 61, 54, 62,...
    ## $ price   <int> 326, 326, 327, 334, 335, 336, 336, 337, 337, 338, 339, 340,...
    ## $ x       <dbl> 3.95, 3.89, 4.05, 4.20, 4.34, 3.94, 3.95, 4.07, 3.87, 4.00,...
    ## $ y       <dbl> 3.98, 3.84, 4.07, 4.23, 4.35, 3.96, 3.98, 4.11, 3.78, 4.05,...
    ## $ z       <dbl> 2.43, 2.31, 2.31, 2.63, 2.75, 2.48, 2.47, 2.53, 2.49, 2.39,...

Primary keys are not immediately obvious, so let’s check the number of
distinct (i.e. unique) rows in the dataset:

``` r
diamonds %>% 
  distinct() %>% 
  nrow()
```

    ## [1] 53794

The number of unique rows is 53,794, which is less than the total rows
(53,940), indicating that there are a number of entirely duplicated
rows. This means that there are no unique identifiers, so we would need
to add a surrogate key.

``` r
diamonds %>% 
  mutate(surrogate_key = row_number(),
         .before = 1)
```

    ## # A tibble: 53,940 x 11
    ##    surrogate_key carat cut     color clarity depth table price     x     y     z
    ##            <int> <dbl> <ord>   <ord> <ord>   <dbl> <dbl> <int> <dbl> <dbl> <dbl>
    ##  1             1 0.23  Ideal   E     SI2      61.5    55   326  3.95  3.98  2.43
    ##  2             2 0.21  Premium E     SI1      59.8    61   326  3.89  3.84  2.31
    ##  3             3 0.23  Good    E     VS1      56.9    65   327  4.05  4.07  2.31
    ##  4             4 0.290 Premium I     VS2      62.4    58   334  4.2   4.23  2.63
    ##  5             5 0.31  Good    J     SI2      63.3    58   335  4.34  4.35  2.75
    ##  6             6 0.24  Very G~ J     VVS2     62.8    57   336  3.94  3.96  2.48
    ##  7             7 0.24  Very G~ I     VVS1     62.3    57   336  3.95  3.98  2.47
    ##  8             8 0.26  Very G~ H     SI1      61.9    55   337  4.07  4.11  2.53
    ##  9             9 0.22  Fair    E     VS2      65.1    61   337  3.87  3.78  2.49
    ## 10            10 0.23  Very G~ H     VS1      59.4    61   338  4     4.05  2.39
    ## # ... with 53,930 more rows

> 3.  Draw a diagram illustrating the connections between the `Batting`,
>     `People`, and `Salaries` tables in the Lahman package.

First, look at the variables in the 3 tables. (Note: `People` was
previously named `Master` and is still referred to as such in the
solutions manual)

``` r
library(Lahman)
```

    ## Warning: package 'Lahman' was built under R version 4.0.3

``` r
glimpse(Batting)
```

    ## Rows: 107,429
    ## Columns: 22
    ## $ playerID <chr> "abercda01", "addybo01", "allisar01", "allisdo01", "ansonc...
    ## $ yearID   <int> 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871...
    ## $ stint    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ teamID   <fct> TRO, RC1, CL1, WS3, RC1, FW1, RC1, BS1, FW1, BS1, CL1, CL1...
    ## $ lgID     <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ G        <int> 1, 25, 29, 27, 25, 12, 1, 31, 1, 18, 22, 1, 10, 3, 20, 29,...
    ## $ AB       <int> 4, 118, 137, 133, 120, 49, 4, 157, 5, 86, 89, 3, 36, 15, 9...
    ## $ R        <int> 0, 30, 28, 28, 29, 9, 0, 66, 1, 13, 18, 0, 6, 7, 24, 26, 0...
    ## $ H        <int> 0, 32, 40, 44, 39, 11, 1, 63, 1, 13, 27, 0, 7, 6, 33, 32, ...
    ## $ X2B      <int> 0, 6, 4, 10, 11, 2, 0, 10, 1, 2, 1, 0, 0, 0, 9, 3, 0, 0, 1...
    ## $ X3B      <int> 0, 0, 5, 2, 3, 1, 0, 9, 0, 1, 10, 0, 0, 0, 1, 3, 0, 0, 1, ...
    ## $ HR       <int> 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0...
    ## $ RBI      <int> 0, 13, 19, 27, 16, 5, 2, 34, 1, 11, 18, 0, 1, 5, 21, 23, 0...
    ## $ SB       <int> 0, 8, 3, 1, 6, 0, 0, 11, 0, 1, 0, 0, 2, 2, 4, 4, 0, 0, 3, ...
    ## $ CS       <int> 0, 1, 1, 1, 2, 1, 0, 6, 0, 0, 1, 0, 0, 0, 0, 4, 0, 0, 1, 0...
    ## $ BB       <int> 0, 4, 2, 0, 2, 0, 1, 13, 0, 0, 3, 1, 2, 0, 2, 9, 0, 0, 4, ...
    ## $ SO       <int> 0, 0, 5, 2, 1, 1, 0, 1, 0, 0, 4, 0, 0, 0, 2, 2, 3, 0, 2, 0...
    ## $ IBB      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ HBP      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ SH       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ SF       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ GIDP     <int> 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0...

``` r
glimpse(People)
```

    ## Rows: 19,878
    ## Columns: 26
    ## $ playerID     <chr> "aardsda01", "aaronha01", "aaronto01", "aasedo01", "ab...
    ## $ birthYear    <int> 1981, 1934, 1939, 1954, 1972, 1985, 1850, 1877, 1869, ...
    ## $ birthMonth   <int> 12, 2, 8, 9, 8, 12, 11, 4, 11, 10, 3, 10, 2, 8, 9, 6, ...
    ## $ birthDay     <int> 27, 5, 5, 8, 25, 17, 4, 15, 11, 14, 16, 22, 16, 17, 19...
    ## $ birthCountry <chr> "USA", "USA", "USA", "USA", "USA", "D.R.", "USA", "USA...
    ## $ birthState   <chr> "CO", "AL", "AL", "CA", "FL", "La Romana", "PA", "PA",...
    ## $ birthCity    <chr> "Denver", "Mobile", "Mobile", "Orange", "Palm Beach", ...
    ## $ deathYear    <int> NA, NA, 1984, NA, NA, NA, 1905, 1957, 1962, 1926, 1930...
    ## $ deathMonth   <int> NA, NA, 8, NA, NA, NA, 5, 1, 6, 4, 2, 6, NA, NA, NA, N...
    ## $ deathDay     <int> NA, NA, 16, NA, NA, NA, 17, 6, 11, 27, 13, 11, NA, NA,...
    ## $ deathCountry <chr> NA, NA, "USA", NA, NA, NA, "USA", "USA", "USA", "USA",...
    ## $ deathState   <chr> NA, NA, "GA", NA, NA, NA, "NJ", "FL", "VT", "CA", "MI"...
    ## $ deathCity    <chr> NA, NA, "Atlanta", NA, NA, NA, "Pemberton", "Fort Laud...
    ## $ nameFirst    <chr> "David", "Hank", "Tommie", "Don", "Andy", "Fernando", ...
    ## $ nameLast     <chr> "Aardsma", "Aaron", "Aaron", "Aase", "Abad", "Abad", "...
    ## $ nameGiven    <chr> "David Allan", "Henry Louis", "Tommie Lee", "Donald Wi...
    ## $ weight       <int> 215, 180, 190, 190, 184, 220, 192, 170, 175, 169, 190,...
    ## $ height       <int> 75, 72, 75, 75, 73, 73, 72, 71, 71, 68, 71, 70, 78, 74...
    ## $ bats         <fct> R, R, R, R, L, L, R, R, R, L, R, R, R, R, L, R, L, L, ...
    ## $ throws       <fct> R, R, R, R, L, L, R, R, R, L, R, R, R, L, L, R, L, R, ...
    ## $ debut        <chr> "2004-04-06", "1954-04-13", "1962-04-10", "1977-07-26"...
    ## $ finalGame    <chr> "2015-08-23", "1976-10-03", "1971-09-26", "1990-10-03"...
    ## $ retroID      <chr> "aardd001", "aaroh101", "aarot101", "aased001", "abada...
    ## $ bbrefID      <chr> "aardsda01", "aaronha01", "aaronto01", "aasedo01", "ab...
    ## $ deathDate    <date> NA, NA, 1984-08-16, NA, NA, NA, 1905-05-17, 1957-01-0...
    ## $ birthDate    <date> 1981-12-27, 1934-02-05, 1939-08-05, 1954-09-08, 1972-...

``` r
glimpse(Salaries)
```

    ## Rows: 26,428
    ## Columns: 5
    ## $ yearID   <int> 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985...
    ## $ teamID   <fct> ATL, ATL, ATL, ATL, ATL, ATL, ATL, ATL, ATL, ATL, ATL, ATL...
    ## $ lgID     <fct> NL, NL, NL, NL, NL, NL, NL, NL, NL, NL, NL, NL, NL, NL, NL...
    ## $ playerID <chr> "barkele01", "bedrost01", "benedbr01", "campri01", "ceronr...
    ## $ salary   <int> 870000, 550000, 545000, 633333, 625000, 800000, 150000, 48...

Figure out unique keys:

``` r
# primary key for Batting, is playerID, yearID, stint

# primary key for People is playerID
n_distinct(People$playerID) == nrow(People)
```

    ## [1] TRUE

``` r
# primary key for Salaries is playerID, yearID, teamID
Salaries %>% 
  count(playerID, yearID, teamID) %>% 
  filter(n > 1)
```

    ## [1] playerID yearID   teamID   n       
    ## <0 rows> (or 0-length row.names)

  - `People$playerID` connects `Batting$playerID` and
    `Salaries$playerID`

See [solutions
manual](https://jrnold.github.io/r4ds-exercise-solutions/relational-data.html#exercise-13.3.3)
for diagrams.

> Draw another diagram that shows the relationship between People,
> Managers, AwardsManagers.

``` r
glimpse(People)
```

    ## Rows: 19,878
    ## Columns: 26
    ## $ playerID     <chr> "aardsda01", "aaronha01", "aaronto01", "aasedo01", "ab...
    ## $ birthYear    <int> 1981, 1934, 1939, 1954, 1972, 1985, 1850, 1877, 1869, ...
    ## $ birthMonth   <int> 12, 2, 8, 9, 8, 12, 11, 4, 11, 10, 3, 10, 2, 8, 9, 6, ...
    ## $ birthDay     <int> 27, 5, 5, 8, 25, 17, 4, 15, 11, 14, 16, 22, 16, 17, 19...
    ## $ birthCountry <chr> "USA", "USA", "USA", "USA", "USA", "D.R.", "USA", "USA...
    ## $ birthState   <chr> "CO", "AL", "AL", "CA", "FL", "La Romana", "PA", "PA",...
    ## $ birthCity    <chr> "Denver", "Mobile", "Mobile", "Orange", "Palm Beach", ...
    ## $ deathYear    <int> NA, NA, 1984, NA, NA, NA, 1905, 1957, 1962, 1926, 1930...
    ## $ deathMonth   <int> NA, NA, 8, NA, NA, NA, 5, 1, 6, 4, 2, 6, NA, NA, NA, N...
    ## $ deathDay     <int> NA, NA, 16, NA, NA, NA, 17, 6, 11, 27, 13, 11, NA, NA,...
    ## $ deathCountry <chr> NA, NA, "USA", NA, NA, NA, "USA", "USA", "USA", "USA",...
    ## $ deathState   <chr> NA, NA, "GA", NA, NA, NA, "NJ", "FL", "VT", "CA", "MI"...
    ## $ deathCity    <chr> NA, NA, "Atlanta", NA, NA, NA, "Pemberton", "Fort Laud...
    ## $ nameFirst    <chr> "David", "Hank", "Tommie", "Don", "Andy", "Fernando", ...
    ## $ nameLast     <chr> "Aardsma", "Aaron", "Aaron", "Aase", "Abad", "Abad", "...
    ## $ nameGiven    <chr> "David Allan", "Henry Louis", "Tommie Lee", "Donald Wi...
    ## $ weight       <int> 215, 180, 190, 190, 184, 220, 192, 170, 175, 169, 190,...
    ## $ height       <int> 75, 72, 75, 75, 73, 73, 72, 71, 71, 68, 71, 70, 78, 74...
    ## $ bats         <fct> R, R, R, R, L, L, R, R, R, L, R, R, R, R, L, R, L, L, ...
    ## $ throws       <fct> R, R, R, R, L, L, R, R, R, L, R, R, R, L, L, R, L, R, ...
    ## $ debut        <chr> "2004-04-06", "1954-04-13", "1962-04-10", "1977-07-26"...
    ## $ finalGame    <chr> "2015-08-23", "1976-10-03", "1971-09-26", "1990-10-03"...
    ## $ retroID      <chr> "aardd001", "aaroh101", "aarot101", "aased001", "abada...
    ## $ bbrefID      <chr> "aardsda01", "aaronha01", "aaronto01", "aasedo01", "ab...
    ## $ deathDate    <date> NA, NA, 1984-08-16, NA, NA, NA, 1905-05-17, 1957-01-0...
    ## $ birthDate    <date> 1981-12-27, 1934-02-05, 1939-08-05, 1954-09-08, 1972-...

``` r
glimpse(Managers)
```

    ## Rows: 3,536
    ## Columns: 10
    ## $ playerID <chr> "wrighha01", "woodji01", "paborch01", "lennobi01", "deaneh...
    ## $ yearID   <int> 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871...
    ## $ teamID   <fct> BS1, CH1, CL1, FW1, FW1, NY2, PH1, RC1, TRO, TRO, WS3, BL1...
    ## $ lgID     <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ inseason <int> 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1...
    ## $ G        <int> 31, 28, 29, 14, 5, 33, 28, 25, 4, 25, 32, 41, 17, 11, 18, ...
    ## $ W        <int> 20, 19, 10, 5, 2, 16, 21, 4, 1, 12, 15, 27, 8, 0, 3, 9, 39...
    ## $ L        <int> 10, 9, 19, 9, 3, 17, 7, 21, 3, 12, 15, 13, 6, 11, 15, 28, ...
    ## $ rank     <int> 3, 2, 8, 8, 8, 5, 1, 9, 6, 6, 4, 2, 2, 9, 9, 7, 1, 7, 7, 9...
    ## $ plyrMgr  <fct> Y, Y, Y, Y, Y, Y, Y, Y, Y, Y, N, Y, Y, Y, Y, Y, Y, Y, Y, Y...

``` r
glimpse(AwardsManagers)
```

    ## Rows: 179
    ## Columns: 6
    ## $ playerID <chr> "larusto01", "lasorto01", "andersp01", "freyji99", "coxbo0...
    ## $ awardID  <chr> "BBWAA Manager of the Year", "BBWAA Manager of the Year", ...
    ## $ yearID   <int> 1983, 1983, 1984, 1984, 1985, 1985, 1986, 1986, 1987, 1987...
    ## $ lgID     <fct> AL, NL, AL, NL, AL, NL, AL, NL, AL, NL, AL, NL, AL, NL, AL...
    ## $ tie      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ notes    <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...

Figure out unique keys:

``` r
# primary key for People is playerID
n_distinct(People$playerID) == nrow(People)
```

    ## [1] TRUE

``` r
# primary key for Manager is playerID, yearID, inseason
Managers %>% 
  count(playerID, yearID, inseason) %>% 
  filter(n > 1)
```

    ## [1] playerID yearID   inseason n       
    ## <0 rows> (or 0-length row.names)

``` r
# primary key for AwardsManagers is playerID, awardID, yearID
AwardsManagers %>% 
  count(playerID, awardID, yearID) %>% 
  filter(n > 1)
```

    ## [1] playerID awardID  yearID   n       
    ## <0 rows> (or 0-length row.names)

Once again, `People$playerID` links to `Managers$playerID` and
`AwardsManagers$playerID`.

> How would you characterise the relationship between the Batting,
> Pitching, and Fielding tables?

The Batting, Pitching, and Fielding observations are connected by
`playerID`, `yearID`, and `stint`. Note that Fielding has an additional
variable in its primary key (`POS` - players can play \>1 position per
stint).

``` r
glimpse(Batting)
```

    ## Rows: 107,429
    ## Columns: 22
    ## $ playerID <chr> "abercda01", "addybo01", "allisar01", "allisdo01", "ansonc...
    ## $ yearID   <int> 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871...
    ## $ stint    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ teamID   <fct> TRO, RC1, CL1, WS3, RC1, FW1, RC1, BS1, FW1, BS1, CL1, CL1...
    ## $ lgID     <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ G        <int> 1, 25, 29, 27, 25, 12, 1, 31, 1, 18, 22, 1, 10, 3, 20, 29,...
    ## $ AB       <int> 4, 118, 137, 133, 120, 49, 4, 157, 5, 86, 89, 3, 36, 15, 9...
    ## $ R        <int> 0, 30, 28, 28, 29, 9, 0, 66, 1, 13, 18, 0, 6, 7, 24, 26, 0...
    ## $ H        <int> 0, 32, 40, 44, 39, 11, 1, 63, 1, 13, 27, 0, 7, 6, 33, 32, ...
    ## $ X2B      <int> 0, 6, 4, 10, 11, 2, 0, 10, 1, 2, 1, 0, 0, 0, 9, 3, 0, 0, 1...
    ## $ X3B      <int> 0, 0, 5, 2, 3, 1, 0, 9, 0, 1, 10, 0, 0, 0, 1, 3, 0, 0, 1, ...
    ## $ HR       <int> 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0...
    ## $ RBI      <int> 0, 13, 19, 27, 16, 5, 2, 34, 1, 11, 18, 0, 1, 5, 21, 23, 0...
    ## $ SB       <int> 0, 8, 3, 1, 6, 0, 0, 11, 0, 1, 0, 0, 2, 2, 4, 4, 0, 0, 3, ...
    ## $ CS       <int> 0, 1, 1, 1, 2, 1, 0, 6, 0, 0, 1, 0, 0, 0, 0, 4, 0, 0, 1, 0...
    ## $ BB       <int> 0, 4, 2, 0, 2, 0, 1, 13, 0, 0, 3, 1, 2, 0, 2, 9, 0, 0, 4, ...
    ## $ SO       <int> 0, 0, 5, 2, 1, 1, 0, 1, 0, 0, 4, 0, 0, 0, 2, 2, 3, 0, 2, 0...
    ## $ IBB      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ HBP      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ SH       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ SF       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ GIDP     <int> 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0...

``` r
glimpse(Pitching)
```

    ## Rows: 47,628
    ## Columns: 30
    ## $ playerID <chr> "bechtge01", "brainas01", "fergubo01", "fishech01", "fleet...
    ## $ yearID   <int> 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871...
    ## $ stint    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ teamID   <fct> PH1, WS3, NY2, RC1, NY2, TRO, RC1, FW1, PH1, TRO, PH1, CL1...
    ## $ lgID     <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ W        <int> 1, 12, 0, 4, 0, 0, 0, 6, 18, 12, 0, 0, 1, 10, 19, 2, 16, 1...
    ## $ L        <int> 2, 15, 0, 16, 1, 0, 1, 11, 5, 15, 0, 2, 0, 17, 10, 0, 16, ...
    ## $ G        <int> 3, 30, 1, 24, 1, 1, 3, 19, 25, 29, 1, 7, 3, 28, 31, 2, 32,...
    ## $ GS       <int> 3, 30, 0, 24, 1, 0, 1, 19, 25, 29, 0, 1, 0, 28, 31, 2, 32,...
    ## $ CG       <int> 2, 30, 0, 22, 1, 0, 1, 19, 25, 28, 0, 1, 0, 22, 22, 2, 31,...
    ## $ SHO      <int> 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0...
    ## $ SV       <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 3, 0, 0...
    ## $ IPouts   <int> 78, 792, 3, 639, 27, 3, 39, 507, 666, 747, 3, 88, 31, 674,...
    ## $ H        <int> 43, 361, 8, 295, 20, 1, 20, 261, 285, 430, 1, 50, 10, 296,...
    ## $ ER       <int> 23, 132, 3, 103, 10, 0, 5, 97, 113, 153, 1, 22, 4, 94, 96,...
    ## $ HR       <int> 0, 4, 0, 3, 0, 0, 0, 5, 3, 4, 0, 4, 0, 9, 2, 0, 7, 0, 6, 4...
    ## $ BB       <int> 11, 37, 0, 31, 3, 0, 3, 21, 40, 75, 2, 6, 3, 47, 38, 8, 39...
    ## $ SO       <int> 1, 13, 0, 15, 0, 0, 1, 17, 15, 12, 0, 0, 0, 34, 23, 0, 22,...
    ## $ BAOpp    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ ERA      <dbl> 7.96, 4.50, 27.00, 4.35, 10.00, 0.00, 3.46, 5.17, 4.58, 5....
    ## $ IBB      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ WP       <int> 7, 7, 2, 20, 0, 0, 1, 15, 3, 44, 1, 2, 5, 48, 11, 0, 15, 3...
    ## $ HBP      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ BK       <int> 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...
    ## $ BFP      <int> 146, 1291, 14, 1080, 57, 3, 70, 876, 1059, 1334, 6, 160, 5...
    ## $ GF       <int> 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 5, 3, 1, 3, 0, 1, 6, 0, 1...
    ## $ R        <int> 42, 292, 9, 257, 21, 0, 30, 243, 223, 362, 1, 53, 8, 288, ...
    ## $ SH       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ SF       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ GIDP     <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...

``` r
glimpse(Fielding)
```

    ## Rows: 143,046
    ## Columns: 18
    ## $ playerID <chr> "abercda01", "addybo01", "addybo01", "allisar01", "allisar...
    ## $ yearID   <int> 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871...
    ## $ stint    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ teamID   <fct> TRO, RC1, RC1, CL1, CL1, WS3, RC1, RC1, RC1, RC1, RC1, FW1...
    ## $ lgID     <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ POS      <chr> "SS", "2B", "SS", "2B", "OF", "C", "1B", "2B", "3B", "C", ...
    ## $ G        <int> 1, 22, 3, 2, 29, 27, 1, 2, 20, 5, 1, 12, 1, 16, 15, 1, 1, ...
    ## $ GS       <int> 1, 22, 3, 0, 29, 27, 0, 1, 19, 4, 1, 12, 1, 16, 15, 1, 0, ...
    ## $ InnOuts  <int> 24, 606, 96, 18, 729, 681, 15, 30, 555, 93, 6, 345, 27, 44...
    ## $ PO       <int> 1, 67, 8, 1, 51, 68, 7, 3, 38, 10, 0, 29, 2, 42, 44, 1, 8,...
    ## $ A        <int> 3, 72, 14, 4, 3, 15, 0, 4, 52, 0, 0, 2, 0, 61, 64, 0, 0, 0...
    ## $ E        <int> 2, 42, 7, 0, 7, 20, 0, 1, 28, 8, 0, 7, 0, 15, 21, 0, 0, 1,...
    ## $ DP       <int> 0, 5, 0, 0, 1, 4, 0, 0, 2, 0, 0, 0, 0, 10, 3, 0, 0, 0, 0, ...
    ## $ PB       <int> NA, NA, NA, NA, NA, 18, NA, NA, NA, 7, NA, NA, NA, NA, NA,...
    ## $ WP       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
    ## $ SB       <int> NA, NA, NA, NA, NA, 0, NA, NA, NA, 0, NA, NA, NA, NA, NA, ...
    ## $ CS       <int> NA, NA, NA, NA, NA, 0, NA, NA, NA, 0, NA, NA, NA, NA, NA, ...
    ## $ ZR       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...

If you’re interested, the [solutions
manual](https://jrnold.github.io/r4ds-exercise-solutions/relational-data.html#exercise-13.3.3)
shows how to generate the actual diagrams using OmniGiraffe software or
the {datamodelr} R package.

The diagrams for the Beat AML database are generated using SchemaSpy.
